In [ ]:
import numpy as np

In [ ]:
a = int(input ('Enter a number. \n'))
print ("Your number is", a, end ='.\n')
print ("lions eat", "tigers")

Enter a number. 
1
Your number is 1.
lions eat tigers


In [ ]:
lst = []*5
for i in range (5):
    a = int(input('Enter a number.'))
    lst.append(a)
print(lst)
print(lst[0])
# int(input('Enter the coefficients of \'x\' in the equations.'))

Enter a number.1
Enter a number.2
Enter a number.3
Enter a number.4
Enter a number.5
[1, 2, 3, 4, 5]
1


In [ ]:
# coefficients of x
lstx = []*2
for i in range (2):
    a = float(input('Enter the coefficients of \'x\' in the equations.'))
    lstx.append(a)
print('\n')

# coefficients of y
lsty = []*2
for i in range (2):
    a = float(input('Enter the coefficients of \'y\' in the equations.'))
    lsty.append(a)
print('\n')

# constant terms in the equations
lstc = []*2
for i in range (2):
    a = float(input('Enter the constants in the equations.'))
    lstc.append(a)
print('\n')

# printing the equations
print('Your equations are:', lstx[0], 'x', '+', lsty[0], 'y', '=', lstc[0])
print('Your equations are:', lstx[1], 'x', '+', lsty[1], 'y', '=', lstc[1])

Enter the coefficients of 'x' in the equations.2
Enter the coefficients of 'x' in the equations.5


Enter the coefficients of 'y' in the equations.4
Enter the coefficients of 'y' in the equations.7


Enter the constants in the equations.3
Enter the constants in the equations.2


Your equations are: 2.0 x + 4.0 y = 3.0
Your equations are: 5.0 x + 7.0 y = 2.0


In [ ]:
# coefficient matrix using a nested list
A = [[lstx [0], lsty [0], lstc [0]], [lstx [1], lsty [1], lstc [1]]]
print (A)

[[2.0, 4.0, 3.0], [5.0, 7.0, 2.0]]


In [ ]:
# coefficient matrix using a numpy array
A = np.array ([[lstx [0], lsty [0], lstc [0]], [lstx [1], lsty [1], lstc [1]]])
print (A)

[[2. 4. 3.]
 [5. 7. 2.]]


In [ ]:
# left cor'o'ner
l_corner = (A[1][0]/A[0][0])
# making the coefficient matrix upper-triangular
A[1][0] = A[1][0] - l_corner*A[0][0]
A[1][1] = A[1][1] - l_corner*A[0][1]
# adjusting the constants' column
A[1][2] = A[1][2] - l_corner*A[0][2]


[[ 2.  4.  3.]
 [ 0. -3.  2.]]


In [ ]:
# making the matrix diagonal
#right cor'o'ner
r_corner = A[0][1]/A[1][1]
A[0][1] = A[0][1] - r_corner*A[1][1]
# adjusting the constants' column
A[0][2] = A[0][2] - r_corner*A[1][2]
print(A)

[[ 2.          0.         -4.33333333]
 [ 0.         -3.         -5.5       ]]


In [ ]:
# making the coefficient matrix unit
A[0][2] = A[0][2]/A[0][0]
A[1][2] = A[1][2]/A[1][1]
#
A[0][0] = A[0][0]/A[0][0]
A[1][1] = A[1][1]/A[1][1]

In [ ]:
print(A)

[[ 1.          0.         -2.16666667]
 [ 0.          1.          1.83333333]]


In [ ]:
print('\'x\' is', A[0][2], end = '.\n')
print('\'y\' is', A[1][2], end = '.\n')

'x' is -2.1666666666666665.
'y' is 1.8333333333333333.
